### ISSUE TITLE
Rectangle tool - change of the stroke color affects only the previously created rectangle not the actual one

### ISSUE THREAD

**Issue by adamtrjn0** [martin19/cloudpaint#21] opened 2022-07-06 17:05 UTC
Description:
Creating a new rectangle of color different than default changes the color of the previously created one, not the actual 
Environment:
Firefox 102.0 64 bit
Preconditions:
1. Browser opened on cloudpaint.com/photo
2. At least one file created

Steps to do:
1. Select the Rectangle Tool
2. Click the drop-down button next to the 'Stroke'
3. Select some color by clicking on it with the left mouse button
4. Click and hold the left mouse button above the workspace 
5. Move the mouse in some direction, then release the left mouse button
6. Repeat steps 4 - 5
Actual result:
A newly created rectangle stroke isn't affected by a color change, the previously created rectangle is instead
Expected result:
Only a newly created rectangle is affected by a color change
Repeatability:
100.0% 10/10

**Comment by martin19** [comment] 2022-10-16 07:16
A rectangle is selected after creation. The Fill/Stroke boxes currently set the fill of the currently selected rectangle.
This works "as intended" but admittedly feels strange to me too. So I leave this open for discussion.

**Comment by martin19** [comment] 2022-10-16 07:19
will close this issue in favour of issue #22

**Closed as completed by martin19** 2022-10-16 07:19 UTC
